Repository DSA8-4/EcoTrade-FE, pull requests merged in 2024-08, with the labels that each got.

#1 메인 페이지 헤더
  index.html
  styles.css
Labels: Feat

#2 loginPage 제작 css 이름 변경
  index.css
  index.html
  login.css
  login.html
Labels: Feat

#3 회원가입 폼 기능 구현
  images/Ecobackground.jpg
  index.css
  index.html
  register.css
  register.html
  register.js
Labels: Fix

#10 상품상세페이지 웹 페이지 구현
  productDetailpage.css
  productDetailpage.html
  productUpdate.css
  productUpdate.html
Labels: Feat

#14 이미지 업로드 firebase 적용
  .gitignore
  .vscode/settings.json
  index.html
  productUpload/index.html
  productUpload/productUpload.js
  utils/firebase.js
Labels: Feat

#17 이미지 업로드 코드 변경
  productUpload/productUpload.js
  register/register.js
Labels: Fix

#18 EcoPoint 웹 페이지
  ETdetail/ETdetail.css
  ETdetail/index.html
  EcoPoint/Ecopoint.css
  EcoPoint/index.html
  images/EcoPoint.PNG
  images/EcoPoint나무심기아이콘.png
  images/EcoPoint친환경상품구매아이콘.png
  images/EcoPoint탄소절감아이콘.png
  index.css
  index.html
  index.js
  login/login.js
  register/register.js
Labels: Feat, Fix

#20 fix productList
  productDetail/index.html
  productDetail/productDetailpage.css
  productDetail/productDetailpage.js
  productList/productList.js
Labels: Feat, Fix
